### ISSUE TITLE
clipboard

### ISSUE THREAD

**Issue by ghost** [KELiON/cerebro-imdb#1]
It would be great if the preview had a button to copy the imdb link to the clipboard for easy sharing.

**Comment by KELiON** [comment]
@horusra hey! You can just use cmd+c on selected item to copy it to clipboard

**Comment by KELiON** [comment]
@horusra but it works only on mac:) It is known bug and will be fixed for linux/windows in next release: https://github.com/KELiON/cerebro/issues/61
