### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by ghost** [KELiON/cerebro-imdb#2]
Using windows 10 64bit. I have the imdb plugin installed, but it refuses to work for some reason.

Am I doing something wrong?

![screenshot](https://cloud.githubusercontent.com/assets/17074394/22790400/60443630-eee6-11e6-8564-ed082489ed04.jpg)
![screenshot](https://cloud.githubusercontent.com/assets/17074394/22790423/7245e162-eee6-11e6-9fe7-ba5d040cb291.jpg)

**Comment by KELiON** [comment]
@horusra hey! This plugin uses unofficial imdb API: [omdb](http://www.omdbapi.com/) and looks like they have some troubles now:

![image](https://cloud.githubusercontent.com/assets/594298/22793074/08c254b0-eeef-11e6-892f-677ccf56577d.png)

**Comment by KELiON** [comment]
@horusra btw, looks like it is not permanent issue, because after several attempts I could get a result: 
![screen shot 2017-02-09 at 17 43 46](https://cloud.githubusercontent.com/assets/594298/22793161/536b747e-eeef-11e6-822f-ddf09c9d1c4d.png)

**Comment by ghost** [comment]
Possibly explore the use of the `imdb` node module which uses screen scraping to retrieve IMDB information? (Doesn't rely on OMDB to be up)

**Comment by hafager** [comment]
Was this issue ever resolved? I have the same problem on Ubuntu. However, it shows up as a suggestion,
<a href="https://ibb.co/hFsNSa"><img src="https://preview.ibb.co/dc6hSa/cerebro_imdb.png" alt="cerebro_imdb" border="0"></a>
but when chosen it shows the same as @horusra . May seem like google is overriding it somehow.

**Comment by KELiON** [comment]
@hafager as I said above this plugin uses [OMDB API](https://www.omdbapi.com/), and looks like recently they went to private type of API:

![image](https://cloud.githubusercontent.com/assets/594298/26589152/8f72e4a2-4557-11e7-9a92-edfc36a6b4e6.png)

It means we will have to figure out what is the better way for our users to use this API.

**Comment by hafager** [comment]
@KELiON ah I see. Thanks.

**Comment by ronan-dean** [comment]
Same issues as above but their website is now showing as open again? Any chance of fixing this?

**Comment by KELiON** [comment]
> Any chance of fixing this?

Done! But the API now supports only 1000 requests per day, so sometimes it can be reached by Cerebro users.

**Comment by KELiON** [comment]
I've added idea to solve this issue in #3
